---
# tasks file for nginx
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Get Nginx port from local Consul
      uri:
        url: "http://localhost:8500/v1/kv/port-nginx?raw"
        return_content: yes
      register: nginx_port_response
      delegate_to: localhost
      become: false

    - name: Set nginx port as fact
      set_fact:
        nginx_port: "{{ nginx_port_response.content }}"

    - name: Print the Nginx port from Consul
      debug:
        msg: "Nginx will run on port: {{ nginx_port_response.content }}"

    - name: Deploy nginx.conf rendered with the selected port
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'
      notify: Restart Nginx

    - name: custom HTML page
      copy:
        src: files/index.html 
        dest: /var/www/html/index.html
      notify: Restart Nginx

